agent:
  amplitudes:
    - np.pi
    - np.pi
    - np.pi
    - np.pi
    - 0.0
  lengths:
    - 0.5
    - 0.5
    - 0.5
    - 0
  fixed_orientation: True
  motor_grid_resolution: 7

environment:
  resolution: 16

dataset:
  n_runs: 30
  n_transitions: 100000
  save_directory: "../.data/FixedOrientationAndAperture.hdf5"

